### ISSUE TITLE
eslint code and add to dev depedencies

### ISSUE THREAD

**Issue by qwo** [AnthonyShalagin/learnYouNode#2]
apply cloudreach eslint configs to all code where sensible.

**Comment by AnthonyShalagin** [comment]
Could you please clarify what you mean by "add to dev dependencies"?

**Comment by qwo** [comment]
Docs can be found [here](https://docs.npmjs.com/files/package.json#devdependencies) but short a `package.json` file can have both dependencies and devDependencies. Often dev dependencies are dependencies you'd only use while "developing" a package. This category includes linters, test frameworks or other instrumentation. 

You can see this really good answer for more info and cases! 

https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies
